export const PLANS = {
  free: {
    name: "Free",
    priceCents: 0,
    productLimit: 50,
    collectionLimit: 3,
    aiFixLimit: 50,
    manualScanLimit: 3,
    scanCadence: "manual" as const,
    features: [
      "Up to 50 products scanned",
      "Up to 3 collections scanned",
      "50 AI & manual fixes (lifetime)",
      "Manual scan only (3 times total)",
      "Basic health dashboard",
    ],
    modules: ["products", "seo", "images", "collections", "fixes", "reports"] as const,
  },
  starter: {
    name: "Starter",
    priceCents: 499,
    productLimit: 300,
    collectionLimit: 50,
    aiFixLimit: 200,
    manualScanLimit: 15,
    scanCadence: "monthly" as const,
    features: [
      "Up to 300 products scanned",
      "Up to 50 collections scanned",
      "200 AI & manual fixes",
      "Auto monthly scan (1× / month)",
      "Manual scans (15 / month)",
      "SEO + product audit",
    ],
    modules: ["products", "seo", "images", "collections", "fixes", "reports"] as const,
  },
  professional: {
    name: "Professional",
    priceCents: 999,
    productLimit: 1000,
    collectionLimit: 500,
    aiFixLimit: 500,
    manualScanLimit: 5,
    scanCadence: "weekly" as const,
    features: [
      "Up to 1,000 products scanned",
      "Up to 500 collections scanned",
      "500 AI & manual fixes",
      "Auto weekly scan (1× / week)",
      "Manual scans (5 / week)",
      "Performance + inventory",
    ],
    modules: [
      "products",
      "seo",
      "images",
      "collections",
      "inventory",
      "performance",
      "fixes",
      "reports",
    ] as const,
  },
  business: {
    name: "Business",
    priceCents: 1999,
    productLimit: 5000,
    collectionLimit: 1000,
    aiFixLimit: 5000,
    manualScanLimit: 2,
    scanCadence: "daily" as const,
    features: [
      "Up to 5,000 products scanned",
      "Up to 1,000 collections scanned",
      "5,000 AI & manual fixes",
      "Auto daily scan (1× / day)",
      "Manual scans (2 / day)",
      "AI assistant",
      "Priority processing",
    ],
    modules: [
      "products",
      "seo",
      "images",
      "collections",
      "inventory",
      "performance",
      "assistant",
      "fixes",
      "reports",
      "stores",
    ] as const,
  },
  enterprise: {
    name: "Enterprise",
    priceCents: 9999,
    productLimit: null,
    collectionLimit: null,
    aiFixLimit: 10000,
    manualScanLimit: 5,
    scanCadence: "daily" as const,
    features: [
      "Unlimited products scanned",
      "Unlimited collections scanned",
      "10,000 AI fix credits & manual fixes",
      "Auto daily scan (1× / day)",
      "Manual scans (5 / day)",
      "AI assistant",
      "Priority processing",
    ],
    modules: ["*"] as const,
  },
} as const;

export type PlanSlug = keyof typeof PLANS;

export const PLAN_RANK: Record<PlanSlug, number> = {
  free: 0,
  starter: 1,
  professional: 2,
  business: 3,
  enterprise: 4,
};

/** Feature keys stored in plan_features (admin-editable). */
export const PLAN_FEATURE_KEYS = [
  { key: "products_limit", label: "Product limit" },
  { key: "collections_limit", label: "Collection limit" },
  { key: "ai_fixes_limit", label: "AI fix limit" },
  { key: "manual_scans_limit", label: "Manual scan limit" },
  { key: "scan_cadence", label: "Scan cadence (0=manual 1=monthly 2=weekly 3=daily)" },
  { key: "module_seo", label: "SEO module" },
  { key: "module_products", label: "Products module" },
  { key: "module_images", label: "Images module" },
  { key: "module_collections", label: "Collections module" },
  { key: "module_inventory", label: "Inventory module" },
  { key: "module_performance", label: "Performance module" },
  { key: "module_assistant", label: "AI assistant" },
  { key: "module_reports", label: "Reports" },
  { key: "email_reports", label: "Email reports (coming later)" },
  { key: "scheduled_reports", label: "Scheduled reports (coming later)" },
] as const;

export function formatPrice(cents: number) {
  if (cents <= 0) return "Free";
  return `$${(cents / 100).toFixed(2)}/mo`;
}
