import type { LoaderFunctionArgs } from "@remix-run/node";
import { Page, Card, BlockStack, Banner, Text, Button, InlineStack } from "@shopify/polaris";
import { TitleBar } from "@shopify/app-bridge-react";
import { count, eq } from "drizzle-orm";
import { authenticate } from "../shopify.server";
import { db } from "../db/client";
import { reportsSent } from "../db/schema";
import { ensureShop } from "../services/shopify/shops.server";
import { DataTable } from "../components/datatable/DataTable";
import { REPORTS_NAV, SubNav } from "../components/SubNav";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const shop = await ensureShop(session.shop, session.accessToken);

  const [{ n }] = await db
    .select({ n: count() })
    .from(reportsSent)
    .where(eq(reportsSent.shopId, shop.id));

  if (n === 0) {
    await db.insert(reportsSent).values([
      {
        shopId: shop.id,
        type: "daily",
        subject: "Daily health digest (sample)",
        summaryJson: JSON.stringify({
          summary: "Sample: 4 products missing images, SEO stable.",
        }),
        sentAt: new Date(Date.now() - 86400000),
      },
      {
        shopId: shop.id,
        type: "weekly",
        subject: "Weekly AI report (sample)",
        summaryJson: JSON.stringify({
          summary: "Sample: Archive 3 dead products. Compress 8 large images.",
        }),
        sentAt: new Date(Date.now() - 7 * 86400000),
      },
    ]);
  }

  return null;
};

export default function ReportsPage() {
  return (
    <Page>
      <TitleBar title="Reports" />
      <SubNav items={REPORTS_NAV} />
      <BlockStack gap="400">
        <Banner tone="info">
          Daily and weekly reports are generated by cron after scans. Sample
          rows appear in development until a real report is sent.
        </Banner>
        <InlineStack align="end">
          <Button url="/app/fixes">Open Fix Queue</Button>
        </InlineStack>
        <Card>
          <DataTable
            table="reportsSent"
            endpoint="/api/app/datatable"
            showViewToggle={false}
          />
        </Card>
        <Text as="p" tone="subdued" variant="bodySm">
          Each row shows type, subject, summary, and sent time.
        </Text>
      </BlockStack>
    </Page>
  );
}
